#!/bin/bash
set -euo pipefail

TEST_CLASSES=""
echo "Scanning for Test Classes"

# Prefer sgd-generated delta if it exists, otherwise compute git diff
if [ -d "Delta-changes/force-app" ] && [ "$(find Delta-changes/force-app -type f | wc -l)" -gt 0 ]; then
echo "Using Delta-changes generated by sgd"
CHANGED_FILES=$(find Delta-changes/force-app -type f | sed 's|^Delta-changes/||')
echo $CHANGED_FILES
else
echo "Computing delta against previous commit..."
CHANGED_FILES=$(git diff --diff-filter=AM --name-only HEAD^ HEAD || true)
echo $CHANGED_FILES
fi

if [ -z "$CHANGED_FILES" ]; then
echo "No added/modified files found. Nothing to deploy."
echo "test_classes=" >> $GITHUB_OUTPUT
exit 0
fi

echo "$CHANGED_FILES" | grep '^force-app/' >/dev/null || {
echo "No changes under force-app. Nothing to deploy."
echo "test_classes=" >> $GITHUB_OUTPUT
exit 0
}

echo "$CHANGED_FILES" | while read -r file; do
echo "Adding $file to Delta-changes"
mkdir -p "Delta-changes/$(dirname "$file")"
cp "$file" "Delta-changes/$file" 2>/dev/null || true

# If this is an Apex class, check if it is a test class (@isTest)
if [[ "$file" == */classes/*.cls ]]; then
if grep -q "@isTest" "$file"; then
classname=$(basename "$file" .cls)
echo "Detected test class: $classname"
if [ -z "$TEST_CLASSES" ]; then
TEST_CLASSES="$classname"
echo $TEST_CLASSES
else
TEST_CLASSES="$TEST_CLASSES,$classname"
echo $TEST_CLASSES
fi
fi
fi
done

# Also scan any class files in the delta directory for @isTest
while IFS= read -r file; do
if grep -q "@isTest" "$file"; then
classname=$(basename "$file" .cls)
if [[ ",${TEST_CLASSES}," != *",${classname},"* ]]; then
if [ -z "$TEST_CLASSES" ]; then
TEST_CLASSES="$classname"
else
TEST_CLASSES="$TEST_CLASSES,$classname"
fi
fi
fi
done < <(find Delta-changes/force-app -name '*.cls' 2>/dev/null || true)

echo "Final test classes: $TEST_CLASSES"
echo "test_classes=$TEST_CLASSES" >> $GITHUB_OUTPUT

echo "Delta contents:"
find Delta-changes || echo "No files in delta."